### ISSUE TITLE
Questions about code

### ISSUE THREAD

**Issue by krmui** [JeyesHan/P2LR#1]
I want to ask why we need to add a resnet.relu layer in self.base on resnet50 model？

**Comment by HelloJianHan** [comment]
Cause it is a relu that in the original resnet. But the relu is forgetten by authors of ReidStrongBaseline (lots of latter works are based on it). In our code, we add the forgetten relu. In deed, the relu doesn't influence much in experimental results as the author of ReidStrongBaseline pointed when they found their mistakes.
