### ISSUE TITLE
Questions about pre training

### ISSUE THREAD

**Issue by krmui** [JeyesHan/P2LR#2]
I found that the accuracy of the pre training dukemtmc to markrt1501 in your code is 29.6, and the effect is not as good as that of 31.8 in MMT. Your paper is improved on the baseline of MMT. I want to ask why you don't keep the pre training of MMT with better effect?

**Comment by HelloJianHan** [comment]
The pretraining of MMT yields fluctuating results. We are not sure whether they selected better pretraining results among multiple runs. However, we found that the final results are not very sentitive to the pretraining results.
