### ISSUE TITLE
dukeTomarket mAP only reach 72.6%

### ISSUE THREAD

**Issue by wangtaos** [JeyesHan/P2LR#5]
> Hello, I would like to ask why the mAP of dukeTomarket I reproduced can only reach 72.6% without any modification of parameters. but only one GPU

**Comment by HelloJianHan** [comment]
We have never tested with 1 gpu during training. But I think it should have similar results in theory. Could you please post the log file during training?

**Comment by wangtaos** [comment]
Thank you very much for your reply to my question. This is the training logs file of my dukeTOmarket1501


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeyesHan/P2LR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeyesHan/P2LR] dukeTomarket mAP only reach 72.6% (Issue #5)





 
We have never tested with 1 gpu during training. But I think it should have similar results in theory. Could you please post the log file during training?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

dukemtmcTOmarket1501_logs.zip (625.38M, 2022年12月24日 08:13 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6739656556d3deb9e338b3164536054e0c5a505702055255180b5c005a1b0359565f48040001054c575b000655035651010d5554632b370540520008175b54357a540417085343500009543a0f5950121b430c15630b&code=59eec67a

**Comment by HelloJianHan** [comment]
I find that your pretrained models (1 gpu during training) perform ~4% lower than mine (4 gpu during training) on Market1501. Yout can try to use my pretrained models and to see if it helps.
Here are duke2market pretrained models:
https://drive.google.com/file/d/1r3Vn8aVjSX-mRKkerFG8ApL6cPVRE1lE/view?usp=sharing

**Comment by wangtaos** [comment]
Ok, I'll try, thanks for your help。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeyesHan/P2LR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeyesHan/P2LR] dukeTomarket mAP only reach 72.6% (Issue #5)





 
I find that your pretrained models (1 gpu during training) perform ~4% lower than mine (4 gpu during training) on Market1501. Yout can try to use my pretrained models and to see if it helps.
 Here are duke2market pretrained models:
 https://drive.google.com/file/d/1r3Vn8aVjSX-mRKkerFG8ApL6cPVRE1lE/view?usp=sharing

**Comment by wangtaos** [comment]
Sorry to bother you again, I had a bit of a problem loading your pretrained model, can you help take a look. I currently use 2 GPUs on my side.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeyesHan/P2LR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeyesHan/P2LR] dukeTomarket mAP only reach 72.6% (Issue #5)





 
I find that your pretrained models (1 gpu during training) perform ~4% lower than mine (4 gpu during training) on Market1501. Yout can try to use my pretrained models and to see if it helps.
 Here are duke2market pretrained models:
 https://drive.google.com/file/d/1r3Vn8aVjSX-mRKkerFG8ApL6cPVRE1lE/view?usp=sharing

**Comment by wangtaos** [comment]
Sorry to bother you again, I had a bit of a problem loading your pretrained model, can you help take a look. I currently use 2 GPUs on my side.
A screenshot of the issue is attached in the attachment




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "JeyesHan/P2LR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月25日(星期五) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeyesHan/P2LR] dukeTomarket mAP only reach 72.6% (Issue #5)





 
I find that your pretrained models (1 gpu during training) perform ~4% lower than mine (4 gpu during training) on Market1501. Yout can try to use my pretrained models and to see if it helps.
 Here are duke2market pretrained models:
 https://drive.google.com/file/d/1r3Vn8aVjSX-mRKkerFG8ApL6cPVRE1lE/view?usp=sharing

**Comment by wangtaos** [comment]
> I find that your pretrained models (1 gpu during training) perform ~4% lower than mine (4 gpu during training) on Market1501. Yout can try to use my pretrained models and to see if it helps. Here are duke2market pretrained models: https://drive.google.com/file/d/1r3Vn8aVjSX-mRKkerFG8ApL6cPVRE1lE/view?usp=sharing

Sorry to bother you again, I had a bit of a problem loading your pretrained model, can you help take a look. I currently use 2 GPUs on my side.
![屏幕截图 2022-12-02 112206](https://user-images.githubusercontent.com/48855779/205230375-b470b816-a99f-4e6e-8b2d-c65bc7bf6b5c.png)

**Comment by HelloJianHan** [comment]
Sorry to hear that. I think the pretrained weights work on previous version of my code. You can try the new weights from the below link.
https://drive.google.com/file/d/1wlu_pFAJXtiaF3UX1fBhhGJdQyaVLAPS/view?usp=sharing
Hope this time it could address your problem~
